# on osx, keep this in sync with llvm_version in meta.yaml.
# linux-aarch hits a compiler bug with GCC 12, upgrade; needs override
# for two versions on linux: one for non-CUDA & one for 11.8
c_compiler_version:            # [unix]
  - 17                         # [osx]
  - 12                         # [linux64]
  - 11                         # [linux64]
  - 13                         # [linux and (aarch64 or ppc64le)]
  - 10                         # [linux and (aarch64 or ppc64le)]
cxx_compiler_version:          # [unix]
  - 17                         # [osx]
  - 12                         # [linux64]
  - 11                         # [linux64]
  - 13                         # [linux and (aarch64 or ppc64le)]
  - 10                         # [linux and (aarch64 or ppc64le)]

# want to test with newer glibc, which requires us to override
# the whole monster zip just to bump c_stdlib_version / docker_image
c_stdlib_version:                                   # [linux]
  - 2.28                                            # [linux]
  - 2.28                                            # [linux]
docker_image:                                       # [linux]
  - quay.io/condaforge/linux-anvil-alma-x86_64:8    # [linux]
  - quay.io/condaforge/linux-anvil-cuda:11.8        # [linux]
# rest just to make smithy happy
fortran_compiler_version:                           # [linux]
  - 12                                              # [linux]
  - 11                                              # [linux]
cdt_name:                                           # [linux]
  - cos7                                            # [linux]
  - cos7                                            # [linux]
cuda_compiler:                                      # [linux]
  - None                                            # [linux]
  - nvcc                                            # [linux]
cuda_compiler_version:                              # [linux]
  - None                                            # [linux]
  - 11.8                                            # [linux]
